credentials:
  consumer_key: 'GoJjP7Xmj4kpxjttr8qJ9cLtC'
  consumer_secret: 'PnbLJGXnJjsE9M97yhHXY2Oyj7ojcrcVulDGM2yQfS05NQjoNK'
  access_key: '2714871673-HF7B4EPK4mWceAuEuBR4TRhJ12AGlJCVS6VPjZb'
  access_secret: 'Yjp80IStjuot5Muvy4SAt2qoaHQdFGQDMJBqD4HQqX1s6'